package com.trm.alarmist.core.system.stopwatch

object Constants {
  const val ACTION_SERVICE_START = "ACTION_SERVICE_START"
  const val ACTION_SERVICE_STOP = "ACTION_SERVICE_STOP"
  const val ACTION_SERVICE_CANCEL = "ACTION_SERVICE_CANCEL"

  const val STOPWATCH_STATE = "STOPWATCH_STATE"

  const val NOTIFICATION_CHANNEL_ID = "STOPWATCH_NOTIFICATION_ID"
  const val NOTIFICATION_CHANNEL_NAME = "STOPWATCH_NOTIFICATION"
  const val NOTIFICATION_ID = 10
}
